# Generated by Django 6.0.6 on 2026-07-02 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('api', 'API')], max_length=10)),
                ('url', models.URLField()),
                ('country', models.CharField(default='BG', max_length=2)),
                ('language', models.CharField(default='bg', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('reviewed', 'Reviewed'), ('published', 'Published'), ('ignored', 'Ignored')], default='imported', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.newssource')),
            ],
            options={
                'ordering': ['-published_at', '-imported_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='news_import_status_5410c9_idx'), models.Index(fields=['source', '-published_at'], name='news_import_source__98b146_idx')],
            },
        ),
    ]
