# Generated by Django 6.0.6 on 2026-07-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
