# Generated by Django 6.0.6 on 2026-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newssource_last_error_newssource_last_imported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedarticle',
            name='source_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
