# Generated by Django 6.0.6 on 2026-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_importedarticle_source_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedarticle',
            name='full_text',
            field=models.TextField(blank=True),
        ),
    ]
